"""Generate JSON component definitions for Arduino AVR boards."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, List, Sequence


OUTPUT_DIR = Path("arduino_ide/component_library/arduino_boards")


@dataclass
class BoardSpec:
    """Description of a board and how to render its pins."""

    filename: str
    identifier: str
    name: str
    description: str
    width: int
    height: int
    digital_count: int
    pwm_pins: Sequence[int]
    analog_count: int
    power_pins: Sequence[tuple[str, str, str]]
    metadata: dict
    component_type: str = "arduino_board"
    digital_step: int = 20
    analog_step: int = 20
    analog_y: int = 120
    power_start_y: int = 40
    power_step_y: int = 20

    def render(self) -> dict:
        pins: List[dict] = []

        for index in range(self.digital_count):
            label = f"D{index}"
            is_pwm = index in self.pwm_pins
            pins.append(
                {
                    "id": label,
                    "label": f"{label}{'~' if is_pwm else ''}",
                    "pin_type": "pwm" if is_pwm else "digital",
                    "position": [index * self.digital_step, 0],
                }
            )

        for index in range(self.analog_count):
            label = f"A{index}"
            pins.append(
                {
                    "id": label,
                    "label": label,
                    "pin_type": "analog",
                    "position": [index * self.analog_step, self.analog_y],
                }
            )

        for offset, (identifier, label, pin_type) in enumerate(self.power_pins):
            pins.append(
                {
                    "id": identifier,
                    "label": label,
                    "pin_type": pin_type,
                    "position": [0, self.power_start_y + offset * self.power_step_y],
                }
            )

        return {
            "id": self.identifier,
            "name": self.name,
            "component_type": self.component_type,
            "description": self.description,
            "width": self.width,
            "height": self.height,
            "pins": pins,
            "metadata": self.metadata,
        }


def dump_board(board: BoardSpec) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUTPUT_DIR / board.filename
    data = board.render()
    path.write_text(json.dumps(data, indent=2) + "\n")


def build_boards() -> Iterable[BoardSpec]:
    """Return all AVR board descriptions."""

    return [
        BoardSpec(
            filename="arduino_uno.json",
            identifier="arduino_uno",
            name="Arduino Uno",
            description="Arduino Uno R3 microcontroller board based on ATmega328P",
            width=260,
            height=160,
            digital_count=14,
            pwm_pins=(3, 5, 6, 9, 10, 11),
            analog_count=6,
            power_pins=(
                ("IOREF", "IOREF", "power"),
                ("RESET", "RESET", "power"),
                ("3V3", "3.3V", "power"),
                ("5V", "5V", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
                ("VIN", "VIN", "power"),
            ),
            metadata={
                "fqbn": "arduino:avr:uno",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega328P",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "input_voltage_recommended": "7-12V",
                "input_voltage_limits": "6-20V",
                "digital_io_pins": 14,
                "pwm_pins": 6,
                "analog_input_pins": 6,
                "flash_memory": "32KB (0.5KB bootloader)",
                "sram": "2KB",
                "eeprom": "1KB",
                "usb_interface": "ATmega16U2",
                "datasheet_url": "https://docs.arduino.cc/hardware/uno-rev3",
                "dimensions_mm": "68.6 x 53.4",
            },
        ),
        BoardSpec(
            filename="arduino_uno_wifi.json",
            identifier="arduino_uno_wifi",
            name="Arduino Uno WiFi",
            description="First-generation Arduino Uno with integrated ESP8266 WiFi module",
            width=260,
            height=160,
            digital_count=14,
            pwm_pins=(3, 5, 6, 9, 10, 11),
            analog_count=6,
            power_pins=(
                ("IOREF", "IOREF", "power"),
                ("RESET", "RESET", "power"),
                ("3V3", "3.3V", "power"),
                ("5V", "5V", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
                ("VIN", "VIN", "power"),
            ),
            metadata={
                "fqbn": "arduino:avr:unoWiFi",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega328P",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "input_voltage_recommended": "7-12V",
                "input_voltage_limits": "6-20V",
                "digital_io_pins": 14,
                "pwm_pins": 6,
                "analog_input_pins": 6,
                "flash_memory": "32KB (0.5KB bootloader)",
                "sram": "2KB",
                "eeprom": "1KB",
                "wireless_module": "ESP8266",
                "usb_interface": "ATmega16U2",
                "datasheet_url": "https://docs.arduino.cc/hardware/uno-wifi",
                "dimensions_mm": "68.6 x 53.4",
            },
        ),
        BoardSpec(
            filename="arduino_mega_2560.json",
            identifier="arduino_mega_2560",
            name="Arduino Mega 2560",
            description="Arduino Mega 2560 board based on the ATmega2560 MCU",
            width=1060,
            height=200,
            digital_count=54,
            pwm_pins=(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 44, 45, 46),
            analog_count=16,
            power_pins=(
                ("IOREF", "IOREF", "power"),
                ("RESET", "RESET", "power"),
                ("3V3", "3.3V", "power"),
                ("5V", "5V", "power"),
                ("VIN", "VIN", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
                ("GND3", "GND", "ground"),
                ("GND4", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:mega",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega2560",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "input_voltage_recommended": "7-12V",
                "input_voltage_limits": "6-20V",
                "digital_io_pins": 54,
                "pwm_pins": 15,
                "analog_input_pins": 16,
                "flash_memory": "256KB (8KB bootloader)",
                "sram": "8KB",
                "eeprom": "4KB",
                "usb_interface": "ATmega16U2",
                "datasheet_url": "https://docs.arduino.cc/hardware/mega-2560-rev3",
                "dimensions_mm": "101.5 x 53.3",
            },
        ),
        BoardSpec(
            filename="arduino_mega_adk.json",
            identifier="arduino_mega_adk",
            name="Arduino Mega ADK",
            description="Arduino Mega ADK board with USB host interface for Android accessories",
            width=1060,
            height=200,
            digital_count=54,
            pwm_pins=(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 44, 45, 46),
            analog_count=16,
            power_pins=(
                ("IOREF", "IOREF", "power"),
                ("RESET", "RESET", "power"),
                ("3V3", "3.3V", "power"),
                ("5V", "5V", "power"),
                ("VIN", "VIN", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
                ("GND3", "GND", "ground"),
                ("GND4", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:megaADK",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega2560",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "input_voltage_recommended": "7-12V",
                "input_voltage_limits": "6-20V",
                "digital_io_pins": 54,
                "pwm_pins": 15,
                "analog_input_pins": 16,
                "flash_memory": "256KB (8KB bootloader)",
                "sram": "8KB",
                "eeprom": "4KB",
                "usb_host": "MAX3421E",
                "datasheet_url": "https://docs.arduino.cc/hardware/mega-adk",
                "dimensions_mm": "101.5 x 53.3",
            },
        ),
        BoardSpec(
            filename="arduino_leonardo.json",
            identifier="arduino_leonardo",
            name="Arduino Leonardo",
            description="Arduino Leonardo board based on the ATmega32u4 with native USB",
            width=300,
            height=160,
            digital_count=20,
            pwm_pins=(3, 5, 6, 9, 10, 11, 13),
            analog_count=12,
            power_pins=(
                ("IOREF", "IOREF", "power"),
                ("RESET", "RESET", "power"),
                ("3V3", "3.3V", "power"),
                ("5V", "5V", "power"),
                ("VIN", "VIN", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:leonardo",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega32u4",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "input_voltage_recommended": "7-12V",
                "digital_io_pins": 20,
                "pwm_pins": 7,
                "analog_input_pins": 12,
                "flash_memory": "32KB (4KB bootloader)",
                "sram": "2.5KB",
                "eeprom": "1KB",
                "usb_interface": "Native USB",
                "datasheet_url": "https://docs.arduino.cc/hardware/leonardo",
                "dimensions_mm": "68.6 x 53.3",
            },
        ),
        BoardSpec(
            filename="arduino_leonardo_eth.json",
            identifier="arduino_leonardo_eth",
            name="Arduino Leonardo ETH",
            description="Arduino Leonardo ETH with integrated Ethernet controller",
            width=320,
            height=160,
            digital_count=20,
            pwm_pins=(3, 5, 6, 9, 10, 11, 13),
            analog_count=12,
            power_pins=(
                ("IOREF", "IOREF", "power"),
                ("RESET", "RESET", "power"),
                ("3V3", "3.3V", "power"),
                ("5V", "5V", "power"),
                ("VIN", "VIN", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:leonardoeth",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega32u4",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "input_voltage_recommended": "7-12V",
                "digital_io_pins": 20,
                "pwm_pins": 7,
                "analog_input_pins": 12,
                "flash_memory": "32KB (4KB bootloader)",
                "sram": "2.5KB",
                "eeprom": "1KB",
                "ethernet_controller": "W5500",
                "datasheet_url": "https://docs.arduino.cc/hardware/leonardo-eth",
                "dimensions_mm": "68.6 x 53.3",
            },
        ),
        BoardSpec(
            filename="arduino_micro.json",
            identifier="arduino_micro",
            name="Arduino Micro",
            description="Compact Arduino Micro board based on the ATmega32u4",
            width=400,
            height=120,
            digital_count=20,
            pwm_pins=(3, 5, 6, 9, 10, 11, 13),
            analog_count=12,
            power_pins=(
                ("RAW", "RAW", "power"),
                ("VCC", "VCC", "power"),
                ("3V3", "3.3V", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:micro",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega32u4",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "input_voltage_limits": "7-12V (RAW)",
                "digital_io_pins": 20,
                "pwm_pins": 7,
                "analog_input_pins": 12,
                "flash_memory": "32KB (4KB bootloader)",
                "sram": "2.5KB",
                "eeprom": "1KB",
                "usb_interface": "Native USB",
                "datasheet_url": "https://docs.arduino.cc/hardware/micro",
                "dimensions_mm": "48 x 18",
            },
        ),
        BoardSpec(
            filename="arduino_esplora.json",
            identifier="arduino_esplora",
            name="Arduino Esplora",
            description="Arduino Esplora gamepad-style board with onboard sensors",
            width=600,
            height=240,
            digital_count=16,
            pwm_pins=(3, 5, 6, 9, 10, 11),
            analog_count=12,
            power_pins=(
                ("5V", "5V", "power"),
                ("3V3", "3.3V", "power"),
                ("VIN", "VIN", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:esplora",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega32u4",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "digital_io_pins": 16,
                "pwm_pins": 6,
                "analog_input_pins": 12,
                "flash_memory": "32KB (4KB bootloader)",
                "sram": "2.5KB",
                "eeprom": "1KB",
                "onboard_features": "Accelerometer, joystick, temperature, microphone, light sensor",
                "datasheet_url": "https://docs.arduino.cc/hardware/esplora",
                "dimensions_mm": "164.6 x 60",
            },
        ),
        BoardSpec(
            filename="arduino_mini.json",
            identifier="arduino_mini",
            name="Arduino Mini",
            description="Arduino Mini board for embedded applications",
            width=280,
            height=120,
            digital_count=14,
            pwm_pins=(3, 5, 6, 9, 10, 11),
            analog_count=8,
            power_pins=(
                ("RAW", "RAW", "power"),
                ("VCC", "VCC", "power"),
                ("3V3", "3.3V", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:mini",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega328P",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "input_voltage_limits": "7-9V (RAW)",
                "digital_io_pins": 14,
                "pwm_pins": 6,
                "analog_input_pins": 8,
                "flash_memory": "32KB (2KB bootloader)",
                "sram": "2KB",
                "eeprom": "1KB",
                "datasheet_url": "https://docs.arduino.cc/hardware/arduino-mini",
                "dimensions_mm": "30 x 18",
            },
        ),
        BoardSpec(
            filename="arduino_nano.json",
            identifier="arduino_nano",
            name="Arduino Nano",
            description="Compact Arduino Nano based on the ATmega328P",
            width=300,
            height=120,
            digital_count=22,
            pwm_pins=(3, 5, 6, 9, 10, 11),
            analog_count=8,
            power_pins=(
                ("VIN", "VIN", "power"),
                ("3V3", "3.3V", "power"),
                ("5V", "5V", "power"),
                ("VUSB", "VUSB", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:nano",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega328P",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "input_voltage_recommended": "7-12V",
                "digital_io_pins": 22,
                "pwm_pins": 6,
                "analog_input_pins": 8,
                "flash_memory": "32KB (2KB bootloader)",
                "sram": "2KB",
                "eeprom": "1KB",
                "usb_interface": "Mini-USB",
                "datasheet_url": "https://docs.arduino.cc/hardware/nano",
                "dimensions_mm": "45 x 18",
            },
        ),
        BoardSpec(
            filename="arduino_ethernet.json",
            identifier="arduino_ethernet",
            name="Arduino Ethernet",
            description="Arduino Ethernet board with integrated W5100 controller",
            width=280,
            height=160,
            digital_count=14,
            pwm_pins=(3, 5, 6, 9, 10, 11),
            analog_count=6,
            power_pins=(
                ("IOREF", "IOREF", "power"),
                ("RESET", "RESET", "power"),
                ("3V3", "3.3V", "power"),
                ("5V", "5V", "power"),
                ("VIN", "VIN", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:ethernet",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega328P",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "input_voltage_recommended": "7-12V",
                "digital_io_pins": 14,
                "pwm_pins": 6,
                "analog_input_pins": 6,
                "flash_memory": "32KB (0.5KB bootloader)",
                "sram": "2KB",
                "eeprom": "1KB",
                "ethernet_controller": "W5100",
                "datasheet_url": "https://docs.arduino.cc/hardware/ethernet-rev3",
                "dimensions_mm": "73 x 54",
            },
        ),
        BoardSpec(
            filename="arduino_fio.json",
            identifier="arduino_fio",
            name="Arduino Fio",
            description="Arduino Fio with XBee socket for wireless projects",
            width=260,
            height=140,
            digital_count=14,
            pwm_pins=(3, 5, 6, 9, 10, 11),
            analog_count=8,
            power_pins=(
                ("RAW", "RAW", "power"),
                ("VCC", "VCC", "power"),
                ("BAT", "BAT", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:fio",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega328P",
                "clock_speed": "8MHz",
                "operating_voltage": "3.3V",
                "input_voltage_limits": "3.35-12V (RAW)",
                "digital_io_pins": 14,
                "pwm_pins": 6,
                "analog_input_pins": 8,
                "flash_memory": "32KB (2KB bootloader)",
                "sram": "2KB",
                "eeprom": "1KB",
                "wireless_socket": "XBee (Series 1/2)",
                "datasheet_url": "https://docs.arduino.cc/hardware/arduino-fio",
                "dimensions_mm": "27.9 x 36.5",
            },
        ),
        BoardSpec(
            filename="arduino_bt.json",
            identifier="arduino_bt",
            name="Arduino BT",
            description="Arduino Bluetooth board with integrated Bluegiga WT11 module",
            width=280,
            height=160,
            digital_count=20,
            pwm_pins=(3, 5, 6, 9, 10, 11),
            analog_count=6,
            power_pins=(
                ("IOREF", "IOREF", "power"),
                ("RESET", "RESET", "power"),
                ("3V3", "3.3V", "power"),
                ("5V", "5V", "power"),
                ("VIN", "VIN", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:bt",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega328P",
                "clock_speed": "8MHz",
                "operating_voltage": "3.3V",
                "input_voltage_recommended": "7-12V",
                "digital_io_pins": 20,
                "pwm_pins": 6,
                "analog_input_pins": 6,
                "flash_memory": "32KB (2KB bootloader)",
                "sram": "2KB",
                "eeprom": "1KB",
                "bluetooth_module": "Bluegiga WT11",
                "datasheet_url": "https://docs.arduino.cc/hardware/arduino-bt",
                "dimensions_mm": "68.6 x 53.4",
            },
        ),
        BoardSpec(
            filename="lilypad_arduino.json",
            identifier="lilypad_arduino",
            name="LilyPad Arduino",
            description="Sewable LilyPad Arduino board for wearable projects",
            width=320,
            height=320,
            digital_count=14,
            pwm_pins=(3, 5, 6, 9, 10, 11),
            analog_count=6,
            power_pins=(
                ("VBATT", "VBATT", "power"),
                ("VCC", "VCC", "power"),
                ("3V3", "3.3V", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:lilypad",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega328P",
                "clock_speed": "8MHz",
                "operating_voltage": "3.3V",
                "input_voltage_limits": "2.7-5.5V",
                "digital_io_pins": 14,
                "pwm_pins": 6,
                "analog_input_pins": 6,
                "flash_memory": "32KB (2KB bootloader)",
                "sram": "2KB",
                "eeprom": "1KB",
                "datasheet_url": "https://docs.arduino.cc/hardware/lilypad-arduino",
                "dimensions_mm": "50 (diameter)",
            },
        ),
        BoardSpec(
            filename="lilypad_arduino_usb.json",
            identifier="lilypad_arduino_usb",
            name="LilyPad Arduino USB",
            description="LilyPad Arduino USB with onboard LiPo charging and native USB",
            width=320,
            height=320,
            digital_count=20,
            pwm_pins=(3, 5, 6, 9, 10, 11, 13),
            analog_count=12,
            power_pins=(
                ("VBATT", "VBATT", "power"),
                ("VCC", "VCC", "power"),
                ("CHG", "CHG", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:lilypadUSB",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega32u4",
                "clock_speed": "8MHz",
                "operating_voltage": "3.3V",
                "digital_io_pins": 20,
                "pwm_pins": 7,
                "analog_input_pins": 12,
                "flash_memory": "32KB (4KB bootloader)",
                "sram": "2.5KB",
                "eeprom": "1KB",
                "charging_circuit": "MCP73831",
                "datasheet_url": "https://docs.arduino.cc/hardware/lilypad-usb",
                "dimensions_mm": "50 (diameter)",
            },
        ),
        BoardSpec(
            filename="lilypad_arduino_simple.json",
            identifier="lilypad_arduino_simple",
            name="LilyPad Arduino Simple",
            description="Simplified LilyPad Arduino with built-in LiPo connector",
            width=320,
            height=320,
            digital_count=9,
            pwm_pins=(3, 5, 6, 9, 10, 11),
            analog_count=4,
            power_pins=(
                ("VBATT", "VBATT", "power"),
                ("VCC", "VCC", "power"),
                ("CHG", "CHG", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:lilypadSimple",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega328P",
                "clock_speed": "8MHz",
                "operating_voltage": "3.3V",
                "digital_io_pins": 9,
                "pwm_pins": 6,
                "analog_input_pins": 4,
                "flash_memory": "32KB (2KB bootloader)",
                "sram": "2KB",
                "eeprom": "1KB",
                "datasheet_url": "https://docs.arduino.cc/hardware/lilypad-simple",
                "dimensions_mm": "50 (diameter)",
            },
        ),
        BoardSpec(
            filename="arduino_pro.json",
            identifier="arduino_pro",
            name="Arduino Pro",
            description="Arduino Pro board available in 3.3V/8MHz and 5V/16MHz variants",
            width=300,
            height=140,
            digital_count=14,
            pwm_pins=(3, 5, 6, 9, 10, 11),
            analog_count=6,
            power_pins=(
                ("RAW", "RAW", "power"),
                ("VCC", "VCC", "power"),
                ("3V3", "3.3V", "power"),
                ("5V", "5V", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:pro",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega328P or ATmega168",
                "clock_speed": "8MHz or 16MHz",
                "operating_voltage": "3.3V or 5V",
                "input_voltage_limits": "6-20V (RAW)",
                "digital_io_pins": 14,
                "pwm_pins": 6,
                "analog_input_pins": 6,
                "flash_memory": "32KB (ATmega328P) / 16KB (ATmega168)",
                "sram": "2KB (ATmega328P) / 1KB (ATmega168)",
                "eeprom": "1KB (ATmega328P) / 512B (ATmega168)",
                "datasheet_url": "https://docs.arduino.cc/hardware/arduino-pro",
                "dimensions_mm": "53.3 x 19",
            },
        ),
        BoardSpec(
            filename="arduino_pro_mini.json",
            identifier="arduino_pro_mini",
            name="Arduino Pro Mini",
            description="Arduino Pro Mini with selectable voltage and clock options",
            width=260,
            height=120,
            digital_count=14,
            pwm_pins=(3, 5, 6, 9, 10, 11),
            analog_count=8,
            power_pins=(
                ("RAW", "RAW", "power"),
                ("VCC", "VCC", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:proMini",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega328P or ATmega168",
                "clock_speed": "8MHz or 16MHz",
                "operating_voltage": "3.3V or 5V",
                "input_voltage_limits": "3.35-12V (RAW)",
                "digital_io_pins": 14,
                "pwm_pins": 6,
                "analog_input_pins": 8,
                "flash_memory": "32KB (ATmega328P) / 16KB (ATmega168)",
                "sram": "2KB (ATmega328P) / 1KB (ATmega168)",
                "eeprom": "1KB (ATmega328P) / 512B (ATmega168)",
                "datasheet_url": "https://docs.arduino.cc/hardware/pro-mini",
                "dimensions_mm": "33 x 18",
            },
        ),
        BoardSpec(
            filename="arduino_duemilanove.json",
            identifier="arduino_duemilanove",
            name="Arduino Duemilanove",
            description="Arduino Duemilanove with ATmega328P",
            width=260,
            height=160,
            digital_count=14,
            pwm_pins=(3, 5, 6, 9, 10, 11),
            analog_count=6,
            power_pins=(
                ("IOREF", "IOREF", "power"),
                ("RESET", "RESET", "power"),
                ("3V3", "3.3V", "power"),
                ("5V", "5V", "power"),
                ("VIN", "VIN", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:atmega328",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega328P",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "input_voltage_recommended": "7-12V",
                "digital_io_pins": 14,
                "pwm_pins": 6,
                "analog_input_pins": 6,
                "flash_memory": "32KB (0.5KB bootloader)",
                "sram": "2KB",
                "eeprom": "1KB",
                "datasheet_url": "https://docs.arduino.cc/hardware/duemilanove",
                "dimensions_mm": "68.6 x 53.4",
            },
        ),
        BoardSpec(
            filename="arduino_diecemila.json",
            identifier="arduino_diecemila",
            name="Arduino Diecimila",
            description="Arduino Diecimila with ATmega168 microcontroller",
            width=260,
            height=160,
            digital_count=14,
            pwm_pins=(3, 5, 6, 9, 10, 11),
            analog_count=6,
            power_pins=(
                ("IOREF", "IOREF", "power"),
                ("RESET", "RESET", "power"),
                ("3V3", "3.3V", "power"),
                ("5V", "5V", "power"),
                ("VIN", "VIN", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:diecimila",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega168",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "input_voltage_recommended": "7-12V",
                "digital_io_pins": 14,
                "pwm_pins": 6,
                "analog_input_pins": 6,
                "flash_memory": "16KB (2KB bootloader)",
                "sram": "1KB",
                "eeprom": "512B",
                "datasheet_url": "https://docs.arduino.cc/hardware/arduino-diecimila",
                "dimensions_mm": "68.6 x 53.4",
            },
        ),
        BoardSpec(
            filename="arduino_ng.json",
            identifier="arduino_ng",
            name="Arduino NG or older",
            description="Legacy Arduino NG board with ATmega8",
            width=260,
            height=160,
            digital_count=14,
            pwm_pins=(3, 5, 6, 9, 10, 11),
            analog_count=6,
            power_pins=(
                ("IOREF", "IOREF", "power"),
                ("RESET", "RESET", "power"),
                ("3V3", "3.3V", "power"),
                ("5V", "5V", "power"),
                ("VIN", "VIN", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:atmegang",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega8",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "input_voltage_recommended": "7-12V",
                "digital_io_pins": 14,
                "pwm_pins": 6,
                "analog_input_pins": 6,
                "flash_memory": "8KB (1KB bootloader)",
                "sram": "1KB",
                "eeprom": "512B",
                "datasheet_url": "https://docs.arduino.cc/hardware/arduino-ng",
                "dimensions_mm": "68.6 x 53.4",
            },
        ),
        BoardSpec(
            filename="arduino_robot_control.json",
            identifier="arduino_robot_control",
            name="Arduino Robot Control Board",
            description="Arduino Robot control board with onboard sensors and LCD",
            width=520,
            height=320,
            digital_count=20,
            pwm_pins=(3, 5, 6, 9, 10, 11, 13),
            analog_count=12,
            power_pins=(
                ("VIN", "VIN", "power"),
                ("5V", "5V", "power"),
                ("3V3", "3.3V", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:robotControl",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega32u4",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "digital_io_pins": 20,
                "pwm_pins": 7,
                "analog_input_pins": 12,
                "flash_memory": "32KB (4KB bootloader)",
                "sram": "2.5KB",
                "eeprom": "1KB",
                "onboard_features": "LCD, accelerometer, IR sensors, buttons",
                "datasheet_url": "https://docs.arduino.cc/hardware/arduino-robot",
                "dimensions_mm": "190 x 170",
            },
        ),
        BoardSpec(
            filename="arduino_robot_motor.json",
            identifier="arduino_robot_motor",
            name="Arduino Robot Motor Board",
            description="Arduino Robot motor board handling high-current motor drivers",
            width=520,
            height=320,
            digital_count=20,
            pwm_pins=(3, 5, 6, 9, 10, 11, 13),
            analog_count=12,
            power_pins=(
                ("VIN", "VIN", "power"),
                ("5V", "5V", "power"),
                ("3V3", "3.3V", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:robotMotor",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega32u4",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "digital_io_pins": 20,
                "pwm_pins": 7,
                "analog_input_pins": 12,
                "flash_memory": "32KB (4KB bootloader)",
                "sram": "2.5KB",
                "eeprom": "1KB",
                "motor_drivers": "Dual L298P H-bridges",
                "datasheet_url": "https://docs.arduino.cc/hardware/arduino-robot",
                "dimensions_mm": "190 x 170",
            },
        ),
        BoardSpec(
            filename="arduino_yun.json",
            identifier="arduino_yun",
            name="Arduino Yún",
            description="Arduino Yún combining ATmega32u4 with Atheros AR9331 Linux SoC",
            width=320,
            height=200,
            digital_count=20,
            pwm_pins=(3, 5, 6, 9, 10, 11, 13),
            analog_count=12,
            power_pins=(
                ("IOREF", "IOREF", "power"),
                ("RESET", "RESET", "power"),
                ("3V3", "3.3V", "power"),
                ("5V", "5V", "power"),
                ("VIN", "VIN", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:yun",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega32u4",
                "companion_processor": "Atheros AR9331",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "digital_io_pins": 20,
                "pwm_pins": 7,
                "analog_input_pins": 12,
                "flash_memory": "32KB (4KB bootloader)",
                "sram": "2.5KB",
                "eeprom": "1KB",
                "wireless": "802.11b/g/n WiFi",
                "datasheet_url": "https://docs.arduino.cc/hardware/yun",
                "dimensions_mm": "73 x 53",
            },
        ),
        BoardSpec(
            filename="arduino_yun_mini.json",
            identifier="arduino_yun_mini",
            name="Arduino Yún Mini",
            description="Compact Arduino Yún Mini with ATmega32u4 and AR9331 module",
            width=280,
            height=140,
            digital_count=20,
            pwm_pins=(3, 5, 6, 9, 10, 11, 13),
            analog_count=12,
            power_pins=(
                ("VIN", "VIN", "power"),
                ("5V", "5V", "power"),
                ("3V3", "3.3V", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:yunmini",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega32u4",
                "companion_processor": "Atheros AR9331",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "digital_io_pins": 20,
                "pwm_pins": 7,
                "analog_input_pins": 12,
                "flash_memory": "32KB (4KB bootloader)",
                "sram": "2.5KB",
                "eeprom": "1KB",
                "wireless": "802.11b/g/n WiFi",
                "datasheet_url": "https://docs.arduino.cc/hardware/yun-mini",
                "dimensions_mm": "30 x 23",
            },
        ),
        BoardSpec(
            filename="arduino_industrial_101.json",
            identifier="arduino_industrial_101",
            name="Arduino Industrial 101",
            description="Industrial 101 module combining ATmega32u4 with AR9331 Linux SoC",
            width=320,
            height=200,
            digital_count=20,
            pwm_pins=(3, 5, 6, 9, 10, 11, 13),
            analog_count=12,
            power_pins=(
                ("VIN", "VIN", "power"),
                ("5V", "5V", "power"),
                ("3V3", "3.3V", "power"),
                ("VUSB", "VUSB", "power"),
                ("GND1", "GND", "ground"),
                ("GND2", "GND", "ground"),
            ),
            metadata={
                "fqbn": "arduino:avr:chiwawa",
                "manufacturer": "Arduino",
                "microcontroller": "ATmega32u4",
                "companion_processor": "Atheros AR9331",
                "clock_speed": "16MHz",
                "operating_voltage": "5V",
                "digital_io_pins": 20,
                "pwm_pins": 7,
                "analog_input_pins": 12,
                "flash_memory": "32KB (4KB bootloader)",
                "sram": "2.5KB",
                "eeprom": "1KB",
                "wireless": "802.11b/g/n WiFi",
                "datasheet_url": "https://docs.arduino.cc/hardware/industrial-101",
                "dimensions_mm": "68.6 x 53.4",
            },
        ),
    ]


def main() -> None:
    for board in build_boards():
        dump_board(board)


if __name__ == "__main__":
    main()
